# Generated by Django 2.2 on 2021-03-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(default='BG', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.CharField(default='ContactNum', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='full_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
    ]
