# Generated by Django 2.2 on 2021-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0002_auto_20210330_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_blood_group',
            field=models.CharField(default='BG', max_length=10),
        ),
    ]
