# Generated by Django 2.2 on 2021-03-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0003_blog_blog_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.CharField(default='Location', max_length=100),
        ),
    ]
