# Generated by Django 2.2 on 2021-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0004_donor_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
